

#ifndef ATVI_VERSION_DESCRIPTION
#	define ATVI_VERSION_DESCRIPTION	""
#endif

#define __ATVI_VERSION_PRODUCT_STRING_INTERNAL3(s) \
    #s

#define __ATVI_VERSION_PRODUCT_STRING_INTERNAL2(p, s, b, f) \
	__ATVI_VERSION_PRODUCT_STRING_INTERNAL3(p.s.b.f)

#define __ATVI_VERSION_PRODUCT_STRING_INTERNAL(p, s, b, f) \
	__ATVI_VERSION_PRODUCT_STRING_INTERNAL2(p, s, b, f)

#define ATVI_VERSION_PRODUCT_STRING	__ATVI_VERSION_PRODUCT_STRING_INTERNAL(ATVI_VERSION_PRODUCT, ATVI_VERSION_SKU, ATVI_VERSION_BUILD, ATVI_VERSION_HOTFIX)

#define ATVI_VERSION_COMPANYNAME		"Activision Publishing, Inc."
#define ATVI_VERSION_COPYRIGHT			"Copyright (C) 2021 Activision Publishing, Inc."

