//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by ShellExt.rc
//
#define IDR_REGISTRY_SHELLPREVIEWHANDLERIMPL 112
#define IDI_ICON_USD                    113
#define IDR_REGISTRY_SHELLTHUMBNAILPROVIDERIMPL 114
#define IDR_REGISTRY_MODULE             115
#define IDD_LOADSCREEN                  116
#define IDB_LOADSCREEN                  118
#define IDR_REGISTRY_SHELLPROPERTYSTOREIMPL 119
#define IDR_XML_PROPDESC_ATVI           123
#define IDS_USD_DOCUMENTATION_LABEL     123
#define IDR_XML_PROPDESC_USD            124
#define IDS_USD_DOCUMENTATION_INVITATIONTEXT 124
#define IDS_USD_DOCUMENTATION_MNEMONICS 125
#define IDB_LOGO                        125
#define IDS_USD_PROPGROUP_USD_LABEL     126
#define IDS_USD_PROPGROUP_ACTIVISION_LABEL 127
#define IDS_USD_ATVISOURCEFILENAME_LABEL 128
#define IDS_USD_ATVISOURCEFILENAME_MNEMONICS 129
#define IDS_USD_ATVIEXPORTDATE_MNEMONICS 130
#define IDS_USD_ATVIEXPORTFILENAME_MNEMONICS 131
#define IDS_USD_ATVIEXPORTAPPLICATION_MNEMONICS 132
#define IDS_USD_ATVIEXPORTUSER_MNEMONICS 133
#define IDS_USD_ATVIEXPORTDATE_LABEL    134
#define IDS_USD_ATVIEXPORTFILENAME_LABEL 135
#define IDS_USD_ATVIEXPORTAPPLICATION_LABEL 136
#define IDS_USD_ATVIEXPORTUSER_LABEL    137
#define IDS_FILE_USD                    138
#define IDS_FILE_USDA                   139
#define IDS_FILE_USDC                   140
#define IDS_FILE_USDZ                   141
#define IDS_SHELL_VIEW                  142
#define IDS_SHELL_EDIT                  143
#define IDS_SHELL_CRATE                 144
#define IDS_SHELL_UNCRATE               145
#define IDS_SHELL_FLATTEN               146
#define IDS_SHELL_REFRESHTHUMBNAIL      147
#define IDS_SHELL_STATS                 148
#define IDS_USD_CUSTOMLAYERDATA_LABEL   149
#define IDS_USD_CUSTOMLAYERDATA_MNEMONICS 150

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        126
#define _APS_NEXT_COMMAND_VALUE         40011
#define _APS_NEXT_CONTROL_VALUE         1001
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
